//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchServisMCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.MistakesPlayer1 = 0;
            this.MistakesPlayer2 = 0;
        }
    
        public int GameId { get; set; }
        public int MatchId { get; set; }
        public Nullable<int> PointsPlayer1 { get; set; }
        public Nullable<int> PointsPlayer2 { get; set; }
        public Nullable<int> MistakesPlayer1 { get; set; }
        public Nullable<int> MistakesPlayer2 { get; set; }
        public int Win { get; set; }
        public int Opening { get; set; }
        public int Dutch { get; set; }
    }
}
