//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchServisMCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int MatchId { get; set; }
        public int Player1_Id { get; set; }
        public int Player2_Id { get; set; }
        public int TournamentId { get; set; }
        public System.DateTime PlayDate { get; set; }
        public Nullable<bool> BonusGamePlayer1 { get; set; }
        public Nullable<bool> BonusGamePlayer2 { get; set; }
        public int FormatBo { get; set; }
    }
}
