//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchServisMCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerSet()
        {
            this.Prize = 0D;
        }
    
        public int EntryId { get; set; }
        public int TournamentId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<double> Ranking { get; set; }
        public string Place { get; set; }
        public Nullable<double> RankingGet { get; set; }
        public Nullable<double> Prize { get; set; }
    }
}
