//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchServisMCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSet
    {
        public int TournamentId { get; set; }
        public int Ranking { get; set; }
        public int PlayerId { get; set; }
    }
}
